### ISSUE TITLE
License Type

### ISSUE THREAD

**Issue by kingoftheconnors** [qwertyuu/unity-ci-example#2]
Hello!

I've been working on getting CircleCI for my unity project working for about a month now, but your project has cleared quite a few of the problems I was having difficulty with.

But I'm still not out of the worst of it!

My most recent test returned:

```
#!/bin/bash -eo pipefail

chmod +x ./ci/test.sh && ./ci/test.sh

+ echo 'Testing game for editmode'
Testing game for editmode
++ pwd
++ pwd
+ xvfb-run --auto-servernum '--server-args=-screen 0 640x480x24' /opt/Unity/Editor/Unity -projectPath /root/project -runTests -testPlatform editmode -testResults /root/project/editmode-results.xml -logFile -batchmode
Initiating legacy licensing moduleUnable to load libnotify

LICENSE SYSTEM [2019321 14:2:25] Next license update check is after 2019-03-16T17:37:02


LICENSE SYSTEM [2019321 14:2:25] d67ac62a4e9340c893bacb6a6bdb31f0 != 

DisplayProgressbar: Unity license
[UnityConnectServicesConfig] config is NOT valid, switching to default
[0321/140226:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[0321/140226:ERROR:sandbox_linux.cc(308)] InitializeSandbox() called with multiple threads in process gpu-process
Cancelling DisplayDialog: Failed to activate/update license. Missing or bad username and password. Please try again using valid credentials or contact support@unity3d.com
This should not be called in batch mode.
 
(Filename: /home/builduser/buildslave/unity/build/Editor/Platform/Linux/EditorUtility.cpp Line: 257)

+ UNITY_EXIT_CODE=1
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 2 ']'
+ '[' 1 -eq 3 ']'
+ echo 'Unexpected exit code 1'
Unexpected exit code 1
```

I'm pretty sure `LICENSE SYSTEM [2019321 14:2:25] ` means that it reads the license, BUT that it's formatted wrong some way.

I used UTF-8 style of encoding on the base64 encoder you provided, using UNIX line endings (note I am using a Windows computer, but since CircleCI uses bash, I thought UNIX endings were what I should use). Did I get something wrong?

I placed the environment in the config.yml file here:
```
version: 2.1

executors:
  unity_exec:
    docker:
      - image: gableroux/unity3d:2018.3.4f1
    environment:
      BUILD_NAME: Broken Fates
      UNITY_LICENSE_CONTENT: LicenseLicenseLicenseLicenseDon'tLookAtMyLicense!LicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicenseLicense
```

while leaving everything else the same. Could that be the wrong place for it?
